envs:
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "True"
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
- key: DJANGO_ALLOWED_HOST
  scope: RUN_AND_BUILD_TIME
  value: .ondigitalocean.app
- key: DEVELOPMENT_MODE
  scope: RUN_AND_BUILD_TIME
  value: "True"
name: sea-turtle-app
region: nyc
services:
- build_command: |-
    python manage.py migrate --no-input
    python manage.py createsuperuser --noinput
  environment_slug: python
  envs:
  envs:
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "True"
  - key: DISABLE_COLLECTSTATIC
    scope: RUN_AND_BUILD_TIME
    value: "1"
  - key: DJANGO_ALLOWED_HOST
    scope: RUN_AND_BUILD_TIME
    value: .ondigitalocean.app
  - key: DEVELOPMENT_MODE
    scope: RUN_AND_BUILD_TIME
    value: "True"
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  - key: POSTGRES_DB
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE}
  - key: POSTGRES_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${db.HOSTNAME}
  - key: POSTGRES_USER
    scope: RUN_AND_BUILD_TIME
    value: ${db.USERNAME}
  - key: POSTGRES_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: ${db.PASSWORD}
  - key: POSTGRES_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${db.PORT}
  - key: DJANGO_SUPERUSER_EMAIL
    scope: RUN_AND_BUILD_TIME
    value: ladboy@ladboy.boi
  - key: DJANGO_SUPERUSER_USERNAME
    scope: RUN_AND_BUILD_TIME
    value: ladboy
  - key: DJANGO_SUPERUSER_PASSWORD
    scope: RUN_TIME
    value: boi321890
  github:
    branch: main
    deploy_on_push: true
    repo: Snowager/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: pythonwebapps-03-superhero
  routes:
  - path: /
  run_command: |-
    python manage.py migrate --no-input
    gunicorn --worker-tmp-dir /dev/shm config.wsgi
    python manage.py createsuperuser --noinput
  source_dir: projects/7
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: Snowager/PythonWebApps
  name: pythonwebapps-03-superhero-stati
  routes:
  - path: /static
  source_dir: projects/7/static
