# Generated by Django 4.1.1 on 2022-10-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
