# Generated by Django 4.1.1 on 2022-10-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_alter_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='image',
        ),
    ]
