# Generated by Django 4.1.1 on 2022-10-08 05:32

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_remove_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ImageField(null=True, upload_to=[pathlib.PurePosixPath('/home/snow/Desktop/uncApps/PythonWebApps/projects/7/static')]),
        ),
    ]
