# Generated by Django 4.1.1 on 2022-10-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='image',
        ),
        migrations.AddField(
            model_name='hero',
            name='alias',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='strength',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='weakness',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
