# Generated by Django 4.1.1 on 2022-10-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0008_article_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ImageField(default='default.png', upload_to='hero_pics'),
        ),
    ]
